version: '3'

services:
  broker-service:
    build:
      context: ./../broker
      dockerfile: ./../broker/broker.Dockerfile
    restart: always
    ports: 
      - "8080:8000"
    deploy:
      mode: replicated
      replicas: 1
  
  auth-service:
    build: 
      context: ./../auth-service
      dockerfile: ./../auth-service/auth-service.Dockerfile
    restart: always
    ports:
      - "8001:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: 'logs'
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd!
    volumes:
      - ./db-data/mongo/:/data/db